# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espresso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drip',
            options={'verbose_name': 'Drip Campaign'},
        ),
        migrations.AlterModelOptions(
            name='querysetrule',
            options={'verbose_name': 'Targeting Rule'},
        ),
        migrations.AlterModelOptions(
            name='sentdrip',
            options={'verbose_name': 'Sent Drip Emails'},
        ),
        migrations.AlterField(
            model_name='drip',
            name='target',
            field=models.CharField(choices=[(b'events', b'events'), (b'people', b'people')], default=b'people', max_length=128),
        ),
        migrations.AlterField(
            model_name='querysetrule',
            name='method_type',
            field=models.CharField(choices=[(b'filter', b'Filter'), (b'exclude', b'Exclude')], default=b'filter', max_length=12, verbose_name=b'Type'),
        ),
    ]
