# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BsdAddresses',
            fields=[
                ('cons_addr_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('is_primary', models.NullBooleanField()),
                ('addr1', models.CharField(max_length=300, blank=True)),
                ('addr2', models.CharField(max_length=300, blank=True)),
                ('addr3', models.CharField(max_length=300, blank=True)),
                ('city', models.CharField(max_length=200, blank=True)),
                ('state_cd', models.CharField(max_length=200, blank=True)),
                ('zip', models.CharField(max_length=30, blank=True)),
                ('zip_4', models.CharField(max_length=20, blank=True)),
                ('country', models.CharField(max_length=2, blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('geom', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Address',
                'db_table': 'bsd_addresses',
                'managed': False,
                'verbose_name_plural': 'Addresses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdEmails',
            fields=[
                ('cons_email_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('is_primary', models.BooleanField()),
                ('email', models.CharField(max_length=255)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Email Address',
                'db_table': 'bsd_emails',
                'managed': False,
                'verbose_name_plural': 'Email Addresses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdEventAttendees',
            fields=[
                ('event_attendee_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('event_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'RSVP',
                'db_table': 'bsd_event_attendees',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdEvents',
            fields=[
                ('event_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('event_id_obfuscated', models.CharField(max_length=16, blank=True)),
                ('flag_approval', models.BooleanField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('venue_name', models.CharField(max_length=300)),
                ('venue_zip', models.CharField(max_length=16, blank=True)),
                ('venue_city', models.CharField(max_length=128)),
                ('venue_state_cd', models.CharField(max_length=100)),
                ('venue_addr1', models.CharField(max_length=255)),
                ('venue_addr2', models.CharField(max_length=255, blank=True)),
                ('venue_country', models.CharField(max_length=2)),
                ('venue_directions', models.TextField(blank=True)),
                ('start_tz', models.CharField(max_length=40, blank=True)),
                ('start_dt', models.DateTimeField(null=True, blank=True)),
                ('duration', models.BigIntegerField(null=True, blank=True)),
                ('capacity', models.BigIntegerField()),
                ('attendee_volunteer_show', models.BigIntegerField()),
                ('attendee_volunteer_message', models.TextField(blank=True)),
                ('is_searchable', models.BigIntegerField()),
                ('public_phone', models.BooleanField()),
                ('contact_phone', models.CharField(max_length=25, blank=True)),
                ('host_receive_rsvp_emails', models.BooleanField()),
                ('rsvp_use_reminder_email', models.BooleanField()),
                ('rsvp_email_reminder_hours', models.BigIntegerField(null=True, blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('geom', models.TextField(blank=True)),
                ('is_official', models.NullBooleanField()),
            ],
            options={
                'verbose_name': 'Event',
                'db_table': 'bsd_events',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdEventShifts',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('event_shift_id', models.BigIntegerField(null=True, blank=True)),
                ('event_id', models.BigIntegerField(null=True, blank=True)),
                ('start_time', models.TimeField(null=True, blank=True)),
                ('start_dt', models.DateTimeField(null=True, blank=True)),
                ('end_time', models.TimeField(null=True, blank=True)),
                ('end_dt', models.DateTimeField(null=True, blank=True)),
                ('capacity', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Event Shift',
                'db_table': 'bsd_event_shifts',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdEventTypes',
            fields=[
                ('event_type_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=128)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Event Type',
                'db_table': 'bsd_event_types',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdGroups',
            fields=[
                ('cons_group_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Group',
                'db_table': 'bsd_groups',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdPeople',
            fields=[
                ('cons_id', models.AutoField(serialize=False, primary_key=True)),
                ('prefix', models.CharField(max_length=16, blank=True)),
                ('firstname', models.CharField(max_length=256, blank=True)),
                ('middlename', models.CharField(max_length=128, blank=True)),
                ('lastname', models.CharField(max_length=256, blank=True)),
                ('suffix', models.CharField(max_length=16, blank=True)),
                ('gender', models.CharField(max_length=1, blank=True)),
                ('birth_dt', models.DateTimeField(null=True, blank=True)),
                ('title', models.CharField(max_length=128, blank=True)),
                ('employer', models.CharField(max_length=128, blank=True)),
                ('occupation', models.CharField(max_length=255, blank=True)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Person',
                'db_table': 'bsd_people',
                'managed': False,
                'verbose_name_plural': 'People',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdPersonBsdGroups',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cons_group_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Group Membership',
                'db_table': 'bsd_person_bsd_groups',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdPersonGcBsdGroups',
            fields=[
                ('gc_bsd_group_id', models.IntegerField()),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('id', models.IntegerField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'bsd_person_gc_bsd_groups',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdPhones',
            fields=[
                ('cons_phone_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('is_primary', models.BooleanField()),
                ('phone', models.CharField(max_length=30)),
                ('isunsub', models.NullBooleanField()),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Phone',
                'db_table': 'bsd_phones',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdSubscriptions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cons_email_chapter_subscription_id', models.BigIntegerField(null=True, blank=True)),
                ('cons_email_id', models.BigIntegerField(null=True, blank=True)),
                ('chapter_id', models.BigIntegerField(null=True, blank=True)),
                ('isunsub', models.NullBooleanField()),
                ('unsub_dt', models.DateTimeField(null=True, blank=True)),
                ('modified_dt', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'db_table': 'bsd_subscriptions',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdSurveyFields',
            fields=[
                ('signup_form_field_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('signup_form_id', models.BigIntegerField()),
                ('stg_signup_column_name', models.CharField(max_length=64, blank=True)),
                ('format', models.IntegerField()),
                ('label', models.CharField(max_length=20000, blank=True)),
                ('display_order', models.IntegerField()),
                ('is_shown', models.BooleanField()),
                ('is_required', models.BooleanField()),
                ('description', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'verbose_name': 'Survey Field',
                'db_table': 'bsd_survey_fields',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BsdSurveys',
            fields=[
                ('signup_form_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('signup_form_slug', models.CharField(max_length=100, blank=True)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Survey',
                'db_table': 'bsd_surveys',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Communications',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('person_id', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Communication',
                'db_table': 'communications',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FastFwdRequest',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('event_id', models.BigIntegerField()),
                ('host_message', models.TextField()),
                ('email_sent_dt', models.DateTimeField(null=True, blank=True)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'FastFwd Request',
                'db_table': 'fast_fwd_request',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('zip', models.CharField(unique=True, max_length=255, blank=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone_offset', models.IntegerField()),
                ('has_dst', models.BooleanField()),
                ('geom', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'zip_codes',
                'managed': False,
            },
            bases=(models.Model,),
        ),
    ]
