# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BsdCallAssignments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField(blank=True, null=True)),
                ('renderer', models.TextField()),
            ],
            options={
                'verbose_name': 'BSD Call Assignment',
                'db_table': 'bsd_call_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GcBsdEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('followup_emailed', models.BooleanField()),
                ('fast_fwd_instructions_sent', models.BooleanField()),
                ('pending_review', models.BooleanField()),
            ],
            options={
                'verbose_name': 'GC BSD Event',
                'db_table': 'gc_bsd_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GcBsdGroups',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('query', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'gc_bsd_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GcBsdSurveys',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('modified_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField()),
                ('processors', models.TextField()),
            ],
            options={
                'db_table': 'gc_bsd_surveys',
                'managed': False,
            },
        ),
    ]
